// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdPzsRWxO7kN72wSfCpX5pcIYBE1gfxg4',
    appId: '1:782984344795:web:e05a419e61ee91822c08fe',
    messagingSenderId: '782984344795',
    projectId: 'toko-sepatu-running',
    authDomain: 'toko-sepatu-running.firebaseapp.com',
    storageBucket: 'toko-sepatu-running.firebasestorage.app',
    measurementId: 'G-ML037V0QCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhP3XgYqxNcsHD0XfW73GnMcOemfSebsY',
    appId: '1:782984344795:android:de92e573b0c99f7d2c08fe',
    messagingSenderId: '782984344795',
    projectId: 'toko-sepatu-running',
    storageBucket: 'toko-sepatu-running.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Jczjk0LsD9R9tPqp02bf8R-zKHRzEco',
    appId: '1:782984344795:ios:0a943bbe435845d82c08fe',
    messagingSenderId: '782984344795',
    projectId: 'toko-sepatu-running',
    storageBucket: 'toko-sepatu-running.firebasestorage.app',
    iosClientId: '782984344795-7010mcre7uu7fsr1d63o4afvgagqvf5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Jczjk0LsD9R9tPqp02bf8R-zKHRzEco',
    appId: '1:782984344795:ios:0a943bbe435845d82c08fe',
    messagingSenderId: '782984344795',
    projectId: 'toko-sepatu-running',
    storageBucket: 'toko-sepatu-running.firebasestorage.app',
    iosClientId: '782984344795-7010mcre7uu7fsr1d63o4afvgagqvf5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appsmarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdPzsRWxO7kN72wSfCpX5pcIYBE1gfxg4',
    appId: '1:782984344795:web:6fec3d79947f62a32c08fe',
    messagingSenderId: '782984344795',
    projectId: 'toko-sepatu-running',
    authDomain: 'toko-sepatu-running.firebaseapp.com',
    storageBucket: 'toko-sepatu-running.firebasestorage.app',
    measurementId: 'G-R7T0EY794T',
  );
}
